<a href="https://colab.research.google.com/github/Dhanyamanogaran/Tasks_Guvi_D12/blob/main/numpy%26pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy


In [1]:
import numpy as np
a=[1,2,3,4]
a_1=np.asarray(a,float)
null=np.zeros((2,2))
id=np.eye(2,2)
one=np.ones((2,2))
print(a_1)
print(null)
print(id)
print(one)
array=np.random.random((3,3))
print(array)
#transpose array
transposed=array.T
print(transposed)
#reshaping
reshape=array.reshape(9,1)
print(reshape)
#slicing
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[1:5])
b=np.random.random((2,2))
print(b)
print(b[1,1:4])
print(b[:,1:3])


[1. 2. 3. 4.]
[[0. 0.]
 [0. 0.]]
[[1. 0.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]]
[[0.63629463 0.48634628 0.26711137]
 [0.10686871 0.17292751 0.51307298]
 [0.95510816 0.79333718 0.82500984]]
[[0.63629463 0.10686871 0.95510816]
 [0.48634628 0.17292751 0.79333718]
 [0.26711137 0.51307298 0.82500984]]
[[0.63629463]
 [0.48634628]
 [0.26711137]
 [0.10686871]
 [0.17292751]
 [0.51307298]
 [0.95510816]
 [0.79333718]
 [0.82500984]]
[2 3 4 5]
[[0.7343176  0.3008112 ]
 [0.5926819  0.78888966]]
[0.78888966]
[[0.3008112 ]
 [0.78888966]]


pandas

In [ ]:
import pandas as pd
dataframe=pd.read_csv("/content/IRIS.csv")
dataframe.head()
print(dataframe)
dataframe.tail()
print(dataframe)
dataframe_drop=dataframe.drop(["sepal_width"],axis=1)
print(dataframe_drop)
data=dataframe.drop([148],axis=0)
print(data)
length=len(data)
print(length)
shape=data.shape
print(shape)
data.loc[3]
data.describe()
data.groupby("sepal_length").mean()


     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]
     sepal_length  sepal_width  petal_length  petal_width         species
0             

sepal_width  petal_length  petal_width
sepal_length                                        
4.3              3.000000      1.100000     0.100000
4.4              3.033333      1.333333     0.200000
4.5              2.300000      1.300000     0.300000
4.6              3.325000      1.325000     0.225000
4.7              3.200000      1.450000     0.200000
4.8              3.180000      1.580000     0.200000
4.9              2.866667      2.283333     0.533333
5.0              3.120000      1.840000     0.430000
5.1              3.477778      1.722222     0.400000
5.2              3.425000      2.075000     0.475000
5.3              3.700000      1.500000     0.200000
5.4              3.550000      2.033333     0.516667
5.5              2.842857      3.228571     0.900000
5.6              2.816667      4.200000     1.416667
5.7              3.100000      3.587500     1.100000
5.8              2.885714      4.071429     1.400000
5.9              3.066667      4.700000     1.700000
6.0              2.733333      4.650000     1.500000
6.1              2.850000      4.750000     1.416667
6.2              2.633333      4.533333     1.533333
6.3              2.855556      5.133333     1.811111
6.4              2.957143      5.157143     1.871429
6.5              3.000000      5.240000     1.900000
6.6              2.950000      4.500000     1.350000
6.7              3.050000      5.262500     1.962500
6.8              3.000000      5.400000     1.933333
6.9              3.125000      5.275000     2.050000
7.0              3.200000      4.700000     1.400000
7.1              3.000000      5.900000     2.100000
7.2              3.266667      5.966667     1.966667
7.3              2.900000      6.300000     1.800000
7.4              2.800000      6.100000     1.900000
7.6              3.000000      6.600000     2.100000
7.7              3.050000      6.600000     2.200000
7.9              3.800000      6.400000     2.000000